### ISSUE TITLE
Error on synchronization 

### ISSUE THREAD

**Issue by pbaranski** [krzys-h/librus-patch#1]
- app downloaded and installed 
- when trying synchronisation the popup errors are presented : 

```
Synchronizacja nie powiodła się  
Nie można połączyć się z serwerem wystąpił błąd LIBRUS_MOBILE_APP_ACCEP_NEEDED
```

see screenshot 
![librus problem](https://cloud.githubusercontent.com/assets/1589986/19468363/31ab35f0-9516-11e6-8793-2cab5c8e7ab9.png)
- the paid additional features are not activated in this case

**Comment by krzys-h** [comment]
I think you have to start the new official version at least once to accept the TOS. If that indeed fixes the issue I will add that to README.

**Comment by pbaranski** [comment]
That's works:) 
I accepted TOS in new app and old one synchronisation works like a charm. 
I updated issue with screenshot.
Issue can be closed.
